### PR TITLE
Update webdriver tests to do withdraw

### LINKED ISSUE #8: Selenium testing for all functionality of the site

### PR DESCRIPTION
**Pull request by brittcyr**
fixes #8

### CODE REVIEW

**Review by DonDuala — COMMENTED** [review]
Mind explaining a bit what this does?

**Comment by brittcyr** [comment]
A few things

Test out withdraw whenever there are tokens to withdraw. This will make it so that these accounts do not run out of tokens even when running a lot of tests

Also upload the html when a test fails

Refactoring and more logging

**Comment by DonDuala** [comment]
Withdraw meaning, users withdrawing from DIPs will be have accurate test transactions?

How would these accounts that hold collateral for withdrawal ever run out of tokens?

**Comment by brittcyr** [comment]
Test user withdrawing from DIPs. Not yet checking the exact amounts, just whether it succeeds.

There arent that many SOL account for testing deposit on mainnet. If it deposits and never withdraws in every test, it will eventually run out of SOL. It still could eventually get switched over into USDC, but that is something we can manually rebalance

**Review by DonDuala — APPROVED** [review]
Interesting ty

**Pull request merged**
