### PR TITLE
feat: add draft light theme

### PR DESCRIPTION
**Pull request by diegofigs**
## Description
PR takes care of taking a minimal approach to transforming original app look n feel into a light theme. Still need to change header logo to exclude text so I can shift whole component to light theme.

image

### CODE REVIEW

**Review by brittcyr — APPROVED** [review]
Still feels like it is related to the main app, so the task is not fully done, but this is plenty for now.

**Comment by brittcyr** [comment]
> agreed, some things I think could improve to make status stand apart from the standard app:
> 
> * make header transparent or light colored at least, text black
> * put price indicator in header, could also replace Lottie with a pure css pulse animation and that's one less dependency as added benefit
> * replace switcher/dropdown combo based on width with constant dropdown, potentially nuke styles and go barebone styles
> * adding slight shadows to components (header, dropdown, table, paginator)
> * perhaps change primary from green to something else?
> * perhaps change bg light cyan to something else?

I dont think just theme changes, I am thinking swapping out the whole design. Not worth the effort now. Maybe if we ever do a redesign of the main app, just leave this a version behind.

**Comment by DonDuala** [comment]
This may be stupid but why not just put a banner below the the header that reads something to the effect of the warning? Seems like overkill to make sure it looks that separate

**Comment by DonDuala** [comment]
But this looks fine to me

**Review by DonDuala — APPROVED** [review]

**Comment by brittcyr** [comment]
> This may be stupid but why not just put a banner below the the header that reads something to the effect of the warning? Seems like overkill to make sure it looks that separate

There should be no confusion that it has dependencies on main app. It is an entirely separate deployment. There is no similar standards for support, no uptime SLO. I am not even sure if we should be linking to it or sharing it.

**Pull request merged**
