### PR TITLE
Report on trades

### PR DESCRIPTION
**Pull request by brittcyr**
In trading_report. yarn run main

It checks all the openbook transactions to find the bids and asks
Checks mango db for tranasactions.
Creates csv files for each
Reports summary stats

When copied over to the app, the csv files show up in the liquidity tab using react-vis to show trading history for the last 24 hours

### CODE REVIEW

**Comment by DonDuala** [comment]
Got it running but requires a bunch of // @ts-ignores

**Comment by DonDuala** [comment]
Little bit more detail of which assets were looking at here would be good. Sell price is confusing?
image

**Comment by DonDuala** [comment]
> Little bit more detail of which assets were looking at here would be good. Sell price is confusing? image

Nvm I get it, that's a net amount

Nit generally trading you say:

Buy Qty for Price, net notional (Price bid for Qty)
Sell Qty at Price, net notional (Qty [offered] at Price)

**Comment by brittcyr** [comment]
> > Little bit more detail of which assets were looking at here would be good. Sell price is confusing? image
> 
> Nvm I get it, that's a net amount
> 
> Nit generally trading you say:
> 
> Buy Qty for Price, net notional (Price bid for Qty) Sell Qty at Price, net notional (Qty [offered] at Price)

Changed to

  console.log(`Bought ${totalBuysAmount} for ${totalBuysValue / (totalBuysAmount + .0000000001)}, net notional: ${totalBuysValue} `);
  console.log(`Sold ${totalSellsAmount} for ${totalSellsValue / (totalSellsAmount + .0000000001)}, net notional: ${totalSellsValue}`);

**Comment by brittcyr** [comment]
> Got it running but requires a bunch of // @ts-ignores

I dont need to add any more. I will check if I need to install some different node modules. Added a tsconfig. Maybe that helps

**Comment by brittcyr** [comment]
Will have a follow up to update the graphs in a github action every day

**Review by DonDuala — APPROVED** [review]

**Pull request merged**
