### PR TITLE
Mm

### PR DESCRIPTION
**Pull request by brittcyr**

### CODE REVIEW

**Comment by DonDuala** [comment]
Negative price?
image

**Comment by DonDuala** [comment]
Vanity but would be helpful to group these by DIP contract and make it clearer the price bought > price sold

**Comment by brittcyr** [comment]
Can flip that to positive if needed. Was just looking at token balance changes from the perspective of mm.

**Comment by brittcyr** [comment]
> Vanity but would be helpful to group these by DIP contract and make it clearer the price bought > price sold

That can be a follow up later. Not clear how to do it comprehensively since we do not always immediately route

It is not the case that price bought > price sold, thats the bug in poller that I was talking about where we sit on these for long enough that bids have changed.

**Comment by DonDuala** [comment]
> Can flip that to positive if needed. Was just looking at token balance changes from the perspective of mm.

None of the other prices are negative though

**Comment by DonDuala** [comment]
> > Vanity but would be helpful to group these by DIP contract and make it clearer the price bought > price sold
> 
> That can be a follow up later. Not clear how to do it comprehensively since we do not always immediately route
> 
> It is not the case that price bought > price sold, thats the bug in poller that I was talking about where we sit on these for long enough that bids have changed.

Right good to flag those. A good stat to track would be time held. If it's less than 1 min but buy > sell price we should alert etc

**Comment by brittcyr** [comment]
> > Can flip that to positive if needed. Was just looking at token balance changes from the perspective of mm.
> 
> None of the other prices are negative though

It just iterates over all the balance changes in whatever order the rpc gives until it finds the right tokens, so could be either way. I added a force to make it positive

**Comment by brittcyr** [comment]
> > > Vanity but would be helpful to group these by DIP contract and make it clearer the price bought > price sold
> > 
> > 
> > That can be a follow up later. Not clear how to do it comprehensively since we do not always immediately route
> > It is not the case that price bought > price sold, thats the bug in poller that I was talking about where we sit on these for long enough that bids have changed.
> 
> Right good to flag those. A good stat to track would be time held. If it's less than 1 min but buy > sell price we should alert etc

I dont plan on doing any stats or alerting on this yet. We are at just a very basic level of monitoring everywhere. Alerting and real production monitoring will come when we do a lot more reliability work.

**Review by DonDuala — APPROVED** [review]

**Pull request merged**
